### ISSUE TITLE
Error cannot import name 'Literal' from 'typing' - gspread 6.0.0, python3.7

### ISSUE THREAD

**Issue by franciscofiguerez** [burnash/gspread#1406]
**Describe the bug**
The new version of gspread does not work with python version 3.7.

The problem is when "from typing import Literal" is imported into "worksheet.py", the 3.7 version of python does not contain that module.

**To Reproduce**
1. use python version 3.7 (anaconda, docker or install)
2. pip install gspread
3. import gspread

**Code example***
No code needed

**Screenshots**
![error](https://github.com/burnash/gspread/assets/17518845/f31ba547-d069-438a-ac04-e66d94932a52)

**Environment info:**
- Python 3.7
- gspread 6.0.0

**Additional context**
The problem can be solved by referencing "typing_extensions":
`from typing_extensions import Literal`
OR

`    try:` 
`        from typing import Literal `
`    except ImportError: `
`        from typing_extensions import Literal `

**Comment by lavigne958** [comment]
Hi I am sorry to tell you latest gspread version gspread-6.0.0 is no more compatible with python-3.7

we made a mistake while releasing the latest version we left the mention _python-3.7_ but we will remove it ASAP.

We recommend you to upgrade your python version to at least python3.8 as 3.7 is now end of life. 

closing this issue.
